### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by reserfodium** [lcurses/lcurses#3]
Hello!
After ./bootstrap and ./configure and call utility **make** with options _all check install_ and I get a lot of errors about ncurses

OS: Arch (Kernel: 4.13.11-1-ARCH)
NCURSES: ncurses-6.0+20170902-2

**Comment by gvvaughan** [comment]
did you forget to install the ncurses headers?  (often in a package named something like ncurses6-dev)

Otherwise there's not enough info in your issue to understand the failure. If you haven't figured out what's wrong in your environment already, feel free to open a new issue with the output containing specific error messages.
